# Generated by Django 3.1.5 on 2021-01-13 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("http_method", models.CharField(max_length=10)),
                ("http_user_agent", models.TextField(default="")),
                ("http_referer", models.TextField(default="")),
                ("request_path", models.URLField(default="")),
                ("query_string", models.TextField(blank=True, default="")),
                ("remote_addr", models.CharField(default="", max_length=100)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.CharField(
                        help_text="Used to filter / group logs.", max_length=100
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Used to identify individual logs.", max_length=100
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
